name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-test-lint:
    name: Build, Lint, Type Check & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install

    - name: Run pre-commit hooks (formatting, lint, typing)
      run: poetry run pre-commit run --all-files

    - name: Run tests with pytest
      run: poetry run pytest --cov=pycleancode --cov-report=term-missing

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        fail_ci_if_error: false
